### ISSUE TITLE
[Feature] Add support for wildcard routes

### ISSUE THREAD

**Issue by pi0neerpat** [herecydev/gatsby-plugin-internationalization#3]
I'd like to make a PR to allow for wildcard routes, eg. for client-only routes and nested routing using the `@reach/router`. I thought I'd start the discussion here before I get too deep into the code.

### Expectation

I want to follow the normal pattern for making client-only routes using `onCreatePage` in `gatsby-node.js`. The `gatsby-plugin-internationalization` plugin will need to be updated to detect this and create the correct pages. 

### Example

In this example I have `/home/settings`, `/home/activity`, `home/referrals` etc. all on the same `/home` page.
```js
// src/pages/home.js
import { Router } from '@reach/router';
// ...
const Home = () => {
return (
     <Router basepath='home'>
        <Activity default path='activity' />
        <Referral path='referrals' />
        <Settings path='settings' />
     </Router>
)
```

```js
// gatsby-node.js
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions;
  if (page.path.match(/^\/home/)) {
    createPage({ ...page, matchPath: '/home/*' });
  }
};
```

**Comment by pi0neerpat** [comment]
Since this plug implements `onCreatePage`, I would need to scan for user's existing `onCreatePage` settings. This sounds like it would cause trouble. So I think we may need to add a setting within the configuration like this

```js
options: {
        // ... other config
        wildCardRoutes: [ "home" ]
      }
```

**Comment by pi0neerpat** [comment]
How are you going about local development? I'm getting issues using `yarn link` or `npm link`
`Multiple "root" queries found: "PagesQuery" and "PagesQuery"`

**Comment by herecydev** [comment]
Thanks for opening this Patrick. I'm going to create a sample to walk through this soon. We can use that as a discussion point for how it could look.

**Comment by pi0neerpat** [comment]
I created one here if that helps 
https://github.com/pi0neerpat/gatsby-plugin-internationalization/blob/feature-support-wildcards/samples/wildcards/src/pages/home.js

**Comment by herecydev** [comment]
@pi0neerpat I've put a [PR together](https://github.com/herecydev/gatsby-plugin-internationalization/pull/4/files) that I think solves this problem, check it out!

**Comment by pi0neerpat** [comment]
Yes this looks like it will work. You were too fast! I can't even get the samples working properly :_( I've tried several different ways. How are you doing it?

My only concern is if it will also work with `onCreatePage` rather than `gatsby-plugin-create-client-paths`. I would test it if I could.

```js
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions;
  if (page.path.match(/^\/home/)) {
    createPage({ ...page, matchPath: '/home/*' });
  }
};
```

I see you made a `LocalizedRouter` wrapper for the router. I think this will be fine since `@reach/router` is unlikely to make breaking changes here. But I think it should be clear its optional. 

```js
import { Router } from '@reach/router';
import { useLocalization } from 'gatsby-plugin-internationalization';

export MyComponent () => {
  const { localizePath, localizedNavigate } = useLocalization();

  // Used to navigate in a menu, etc.
  const onClick = id => {
      localizedNavigate(`/app/${id}`);
   };

  return (
    <Router basepath={localizePath("/app")}>
      <Details path="/details" />
      <Settings path="/settings" />
    </Router>
  )
}
```

**Comment by herecydev** [comment]
> Yes this looks like it will work. You were too fast! I can't even get the samples working properly :_( I've tried several different ways. How are you doing it?

Honestly, the simplest way I've found is copy paste 🤫. I need to work on finding a better way for sure.

> But I think it should be clear its optional.

Yep I need to put some docs together for this and explain that it's just a convenice wrapper and the consumer is welcome to right their own as I've provided all the tools to make that work.

> My only concern is if it will also work with onCreatePage rather than gatsby-plugin-create-client-paths. I would test it if I could.

This will break I'm pretty sure. So the reason this works, and again I need to document, is that plugins get executed in order. This is fine with the approach I've taken but site plugins are always executed last. I'll take some time to think about it

**Comment by herecydev** [comment]
I think there's no reason not to ship these changes, I do acknowledge that someone could manually add matchPaths after this plugin is run, for which I will create another issue which will separately track that use case. The thing is at the moment I don't see why you wouldn't use the official plugin which has better error handling anyway

**Comment by pi0neerpat** [comment]
Sounds good to me! No further comments

**Comment by herecydev** [comment]
@pi0neerpat I've pushed that out as a new release. Let me know if it all works for you!

**Comment by pi0neerpat** [comment]
Works great! Thanks for your hard work and patience!
